packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.3.0+sha512-jOHtsax1haxeFFfpKUaEV2U0qY4cwNmGLNls4h2K4oRMP+9FHyuVd6e0v1Dcx1olKOK8C89rgOYSsWs0PwVhWA==
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - msgpackr-extract
preferFrozenLockfile: true
publicHoistPattern:
  - "@commitlint/cli"
  - "@commitlint/config-conventional"
  - "@commitlint/cz-commitlint"
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
